config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => '/cable'

  resources :urls

  resources :batch_metrics, only: [:destroy]

  get '/batch_stats' => 'batch_metrics#batch_stats', as: :batch_stats
  get '/upload_status' => 'batch_metrics#upload_status', as: :upload_status
  get '/batch_urls' => 'batch_metrics#batch_urls', as: :batch_urls

  get '/download' => 'download_csv#download_sample_csv', as: :download_csv
  get 'home' => 'home#index', as: :home
  get 'rate_limit_exceeded' => 'errors#rate_limit_exceeded', as: :rate_limit_exceeded

  root 'urls#index'
end

app/models/url.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: urls
#
#  id           :uuid             not null, primary key
#  click        :integer          default(0)
#  deleted      :boolean          default(FALSE)
#  long_url     :string
#  short_url    :string
#  visits_count :integer          default(0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  batch_id     :uuid             not null
#  user_id      :uuid             not null
#
# Indexes
#
#  index_urls_on_batch_id  (batch_id)
#  index_urls_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (batch_id => batches.id)
#  fk_rails_...  (user_id => users.id)
#

class Url < ApplicationRecord
  include Taggable

  belongs_to :batch
  belongs_to :user
  validates :long_url, presence: true, length: { minimum: 30 }
  validates :user_id, :batch_id, :short_url, presence: true

  scope :active, -> { where(deleted: false) }
  scope :recently_created, -> { order(updated_at: :desc) }
  has_many :visits, dependent: :destroy

  scope :active, -> { where(deleted: false) }

  def self.tag_names_for(user)
    user.urls.joins(:tags).distinct.pluck(:name)
  end

  def self.with_tags(tag_names)
    joins(:tags)
      .where(tags: { name: tag_names })
      .group('urls.id')
      .having('COUNT(tags.id) = ?', tag_names.count)
      .order(updated_at: :desc)
  end

  def log_visit(user, ip_address)
      visits.create!(user: user, ip_address: ip_address)
      true
  rescue StandardError => e
    Rails.logger.error("Error logging visit: #{e.message}")
    false
  end

  def update_tags(tag_names)
    tag_names = tag_names.split(',').map(&:strip).reject(&:blank?).map(&:downcase)
    current_tags = tags.pluck(:name)

    new_tags = tag_names - current_tags
    old_tags = current_tags - tag_names

    tags.where(name: old_tags).destroy_all
    new_tags.each { |name| tags.find_or_create_by(name: name) }
  end
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

# UrlsController controller
class UrlsController < ApplicationController
  require 'securerandom'
  before_action :set_url, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show]
  before_action :rate_limit, only: %i[show]

  def index
    return redirect_to home_path unless user_signed_in?

    @tags = Url.tag_names_for(current_user)
    if params[:tags].present?
      selected_tags = params[:tags].map(&:strip).reject(&:blank?)
      @urls = current_user.urls
                         .with_tags(selected_tags)
                         .page(params[:page])
    else
      @urls = current_user.urls.order(updated_at: :desc).page(params[:page])
    end
  end

  def show
    if @url.log_visit(current_user, request.remote_ip)
      respond_to do |format|
        format.html do
          render inline: <<-HTML.strip_heredoc
            <script>
              var longUrl = '<%= j @url.long_url %>';
              window.open(longUrl, '_blank');
              window.location = '<%= j root_path %>';
            </script>
          HTML
        end
      end
    else
      flash[:alert] = "Failed to track URL visit."
      redirect_to root_path
    end
  end

  def new
    @new_url = Url.new
  end

  def create
    if file_missing?
      flash[:alert] = 'Oops! File missing'
      return redirect_to new_url_path
    end

    base_url = request.base_url
    file = url_params[:file]
    begin
      FileWriterService.call(
        file: file,
        base_url: base_url,
        current_user: current_user
      )
      redirect_to new_url_path, alert: 'File upload in progress. Hold tight'
    rescue StandardError => e
      logger.error("Error while processing file upload: #{e.message}")
      redirect_to new_url_path, alert: 'Error occurred during upload. Please try again later.'
    end
  end

  def edit;end

  def update
    if @url.update(url_params)
      @url.update_tags(params[:url][:tag_names])
      redirect_to urls_path, alert: 'URL was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @url.update(deleted: true)
      flash[:alert] = "Url marked as deleted successfully."
    else
      flash[:error] = "Failed to mark batch as deleted."
    end
    redirect_to urls_path
  end

  private

  def rate_limit
    user_identifier = current_user ? "user:#{current_user.id}" : "ip:#{request.remote_ip}"
    if RateLimiterService.rate_limit_exceeded?(user_identifier:)
      flash[:alert] = "Rate limit exceeded."
      redirect_to rate_limit_exceeded_path
    end
  end

  def url_params
    params.require(:url).permit(:file, :long_url, :short_url, tag_names: [])
  end

  def file_missing?
    params[:url].blank? || params[:url][:file].blank?
  end

  def set_url
    @url = Url.active.find(params[:id])
  end
end

app/views/urls/_import_notification.html.erb
<%# app/views/urls/_import_notification.html.erb %>
<div id="progress-bar-<%= batch.id %>" class="progress" style="visibility: hidden;">
  <div class="progress-bar bg-success" id="progress-width-<%= batch.id %>" role="progressbar" style="width: 0%;">
    <span id="progress-text-<%= batch.id %>">Warming up...</span>
  </div>
</div>
<div>
  <p>The upload is <span id="progress-text-percentage-<%= batch.id %>">0%</span> processed.</p>
</div>

app/views/urls/_url.html.erb
<div id="<%= dom_id(url) %>">
  <div class="card">
    <div class="card-body">
      <p>
        <strong>Short URL:</strong>
        <button type="button" class="btn btn-link" onclick="handleRedirect('<%= url.short_url %>')">
          <%= url.short_url %>
        </button>
      </p>
      <p>
        <strong> Visits Count:</strong>
        <%= url.visits_count %>
      </p>
      <% if url.tags.present? %>
        <p>
          <strong>Tags:</strong>
          <% url.tags.each do |tag| %>
            <span class="badge bg-primary"><%= tag.name %></span>
          <% end %>
        </p>
      <% end %>
      <div class="url-buttons">
        <%= link_to 'Edit', edit_url_path(url), class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" onclick="copyToClipboard('<%= url.short_url %>')">
          <i class="bi bi-clipboard"></i> Share
        </button>
        <%= button_to 'Delete', url_path(url), method: :delete, data: { turbo_confirm: "Are you sure you want to delete URL?" }, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  <br/>
</div>

<script>
  function handleRedirect(shortUrl) {
    var longUrl = '<%= url_path(id: url.id) %>';
    window.location.href = longUrl;
  }

  function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(function() {
      alert('Copied to clipboard!');
    }, function(err) {
      console.error('Async: Could not copy text: ', err);
    });
  }
</script>

app/views/urls/edit.html.erb
<div class="container d-flex align-items-center justify-content-center mt-4">
  <%= form_with(model: @url, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :long_url, style: "display: block" %>
      <%= form.text_field :long_url, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :short_url, style: "display: block" %>
      <%= form.text_field :short_url, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :tags, style: "display: block" %>
      <%= form.text_field :tag_names, class: "form-control", value: @url.tags.pluck(:name).join(', ') %>
      <small class="form-text text-muted">Enter tags separated by commas.</small>
    </div>

    <div>
      <%= form.submit "Update URL", class: "btn btn-primary mt-4" %>
    </div>
  <% end %>
</div>

app/views/urls/index.html.erb
<!-- app/views/urls/index.html.erb -->
<div class="container mt-4">
  <% if @urls.empty? %>
    <div class="container d-flex align-items-center justify-content-center">
      <div class="alert alert-primary" role="alert">
        Sorry, not sure if this is what you expected, but you do not have any URLs yet!
      </div>
    </div>
  <% else %>
    <div class="row">
      <!-- Filter Sidebar -->
      <% if @urls.present? %>
        <div class="col-md-3">
          <div class="filter-tags mb-4">
            <h5>Filter by Tags</h5>
            <%= form_with url: urls_path, method: :get, local: true do |f| %>
              <% @tags.each do |tag| %>
                <div class="form-check">
                  <%= check_box_tag 'tags[]', tag, params[:tags]&.include?(tag),
                    class: "form-check-input", id: "tag-#{tag}" %>
                  <%= label_tag "tag-#{tag}", tag, class: "form-check-label" %>
                </div>
              <% end %>
              <div class="mt-3">
                <%= f.submit "Apply Filters", class: "btn btn-primary" %>
                <%= link_to 'Clear Filters', urls_path, class: "btn btn-secondary ml-2" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>

      <!-- URL Listings -->
      <div class="col-md-9">
          <% @urls.each do |url| %>
            <%= render url %>
          <% end %>

          <!-- Pagination Controls -->
          <div class="d-flex justify-content-center mt-4">
            <%= link_to_prev_page @urls, 'Prev Page', class: "btn btn-primary mx-2" %>
            <%= link_to_next_page @urls, 'Next Page', class: "btn btn-primary mx-2" %>
          </div>
      </div>
    </div>
    <% end %>
</div>

app/views/urls/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div id="upload-status"></div>
    </div>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-md-6">
      <div class="upload-form">
        <%= form_for @new_url, url: urls_path, html: { data: { turbo: true } } do |f| %>
          <div class="form-group d-flex align-items-center justify-content-center">
            <%= f.file_field :file, accept: ".csv", class: "form-control" %>
          </div>
          <div class="actions mt-4">
            <%= f.button "Upload File", type: :submit, class: "btn btn-primary mr-2" %>
          </div>
        <% end %>
        <p class=" mt-4">
          You can click <a href="/download/">here</a> to download a sample CSV file.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/urls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @url %>