config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => '/cable'

  resources :urls

  resources :batch_metrics, only: [:destroy]

  get '/batch_stats' => 'batch_metrics#batch_stats', as: :batch_stats
  get '/upload_status' => 'batch_metrics#upload_status', as: :upload_status
  get '/batch_urls' => 'batch_metrics#batch_urls', as: :batch_urls

  get '/download' => 'download_csv#download_sample_csv', as: :download_csv
  get 'home' => 'home#index', as: :home
  get 'rate_limit_exceeded' => 'errors#rate_limit_exceeded', as: :rate_limit_exceeded

  root 'urls#index'
end

app/controllers/batch_metrics_controller.rb
# frozen_string_literal: true

# BatchMetricsController controller
class BatchMetricsController < ApplicationController
  before_action :set_batch, only: %i[batch_urls destroy]
  before_action :authenticate_user!

  def batch_urls        
    @tags = current_user.urls
                        .joins(:tags)
                        .distinct
                        .pluck(:name)
    @urls = @batch.urls
                  .active
                  .recently_created
                  .page(params[:page])
  
    render template: 'batch_metrics/batch_urls', locals: { urls: @urls, batch: @batch }
  end
  
  def batch_stats
    @batches = current_user.batches
    .active
    .recently_created
    .page(params[:page])
    render template: 'batch_metrics/batch_metrics', locals: { batches: @batches }
  end

  def upload_status
    @batches = current_user.batches.where(success_rate: nil, deleted: false).order(created_at: :desc)
    logger.info "batch_stats #{@batches.count}"
    return render template: 'batch_metrics/batch_not_found' if @batches.empty?

    render template: 'upload_status/upload_status', locals: { batches: @batches }
  end

  def destroy
    if @batch.update(deleted: true)
      flash[:alert] = "Batch marked as deleted successfully."
    else
      flash[:error] = "Failed to mark batch as deleted."
    end
    redirect_to batch_stats_path
  end

  private

  def set_batch
    @batch = Batch.active.find(params[:id])
  end
end

app/views/batch_metrics/_batch.html.erb
<div id="<%= dom_id batch %>">
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="heading<%= batch.id %>">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne<%= batch.id %>" aria-expanded="true" aria-controls="collapseOne<%= batch.id %>">
          <p>Batch ID: <%= batch.id %></p>
        </button>
      </h2>
      <div id="collapseOne<%= batch.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= batch.id %>" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <div class="container">
            <div class="card">
              <div class="card-body">
                <% if batch.success_rate.nil? %>
                  <div class="alert alert-primary" role="alert">
                    Uploading!
                  </div>
                  <p>
                    <%= link_to "View Progress", upload_status_path, class: "btn btn-primary" %>
                  </p>
                <% else %>
                  <p><strong>Batch name:</strong> <%= batch.name %></p>
                  <p><strong>Success Percentage:</strong> <%= batch.success_rate %></p>
                  <p><strong>Failed Count:</strong> <%= batch.failed_urls.size %></p>
                  <div class="d-flex justify-content-between">
                    <p>
                      <%= link_to "View Batch Urls", batch_urls_path(id: batch.id), class: "btn btn-primary" %>
                    </p>
                    <p class="ml-auto">
                      <%= button_to "Delete Batch", batch_metric_path(id: batch.id), method: :delete, data: { turbo_confirm: "Are you sure you want to delete the batch?" }, class: "btn btn-danger" %>
                    </p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br/>

app/views/batch_metrics/batch_metrics.html.erb
<div class="container">
  <% if @batches.size == 0 %>
    <br/>
    <br/>
    <div class="container d-flex align-items-center justify-content-center">
      <div class="alert alert-primary" role="alert">
        Sorry, not sure if this is what you expected, but you do not have any batch metrics yet!
      </div>
    </div>
  <% else %>
    <h1 class="batch-metrics-header text-center">Batch Metrics</h1>
    <div id="batches">
      <% @batches.each do |batch| %>
        <%= render partial: 'batch', locals: { batch: batch } %>
      <% end %>
    </div>
    <%= link_to_prev_page @batches, 'Prev Page', class: "btn btn-primary" %>
    <%= link_to_next_page @batches, 'Next Page', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/batch_metrics/batch_not_found.html.erb
      
<div class="container d-flex align-items-center justify-content-center">
  <div class="alert alert-primary" role="alert">
    Sorry, batch number not found!
  </div>
</div>

app/views/batch_metrics/batch_urls.html.erb
<div class="container mt-4">
  <div class="row">
    <!-- Filter Sidebar -->
    <div class="col-md-3">
      <div class="filter-tags mb-4">
        <h5>Filter by Tags</h5>
        <%= form_with url: urls_path, method: :get, local: true do |f| %>
          <% @tags.each do |tag| %>
            <div class="form-check">
              <%= check_box_tag 'tags[]', tag, params[:tags]&.include?(tag), 
                 class: "form-check-input", id: "tag-#{tag}" %>
              <%= label_tag "tag-#{tag}", tag, class: "form-check-label" %>
            </div>
          <% end %>
          <div class="mt-3">
            <%= f.submit "Apply Filters", class: "btn btn-primary" %>
            <%= link_to 'Clear Filters', urls_path, class: "btn btn-secondary ml-2" %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- URL Listings -->
    <div class="col-md-9">
      <% urls.each do |url| %>
        <%= render url %>
      <% end %>
    </div>
  </div>

  <!-- Pagination Controls -->
  <div class="d-flex justify-content-center mt-4">
    <%= link_to_prev_page urls, 'Prev Page', class: "btn btn-primary mx-2" %>
    <%= link_to_next_page urls, 'Next Page', class: "btn btn-primary mx-2" %>
  </div>
</div>