config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => '/cable'

  resources :urls

  resources :batch_metrics, only: [:destroy]

  get '/batch_stats' => 'batch_metrics#batch_stats', as: :batch_stats
  get '/upload_status' => 'batch_metrics#upload_status', as: :upload_status
  get '/batch_urls' => 'batch_metrics#batch_urls', as: :batch_urls

  get '/download' => 'download_csv#download_sample_csv', as: :download_csv
  get 'home' => 'home#index', as: :home
  get 'rate_limit_exceeded' => 'errors#rate_limit_exceeded', as: :rate_limit_exceeded

  root 'urls#index'
end

app/views/layouts/_alerts.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <div class="alert alert-primary" role="alert">
        <%= alert %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary navbar-custom">
  <div class="container-fluid">
    <%= link_to "URLS Shortener", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
      data-bs-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" 
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if !current_user %>
          <li class="nav-item">
            <%= link_to "Home", home_path, class: 'nav-link' %>
          </li>
        <% end %>

        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Batch Metrics", batch_stats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Urls", urls_path, class: "nav-link" %>
          </li>
          <li class="nav-item" id="upload-url-item">
            <%= link_to "Upload Urls", new_url_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "View Uploads", upload_status_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortnerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar'  %>
      <%= render 'layouts/alerts'  %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>